apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ebat_aws?????????????????????zxcw
  region: eu-north-1

nodeGroups:
  - name: worker-1
    instanceType: t2.micro
    desiredCapacity: 1
  - name: worker-2
    instanceType: t2.micro
    desiredCapacity: 1
  - name: master-1
    instanceType: t2.micro
    desiredCapacity: 1
  - name: master-2
    instanceType: t2.micro
    desiredCapacity: 1
  - name: worker-3
    instanceType: t2.micro
    desiredCapacity: 1
  - name: ingress-1
    instanceType: t2.micro
    desiredCapacity: 1
  - name: ingress-2
    instanceType: t2.micro
    desiredCapacity: 1
